import type { Metadata } from 'next';
import { Fjord_One } from 'next/font/google';
import './globals.css';

const fjordOne = Fjord_One({ weight: '400', subsets: ['latin'], display: 'swap', adjustFontFallback: false });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fjordOne.className}>{children}</body>
    </html>
  );
}
